In [2]:
from pipeline import *

/usr/local/lib/python3.6/dist-packages/tqdm/autonotebook/__init__.py:14: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  " (e.g. in jupyter console)", TqdmExperimentalWarning)

In [ ]:
ppl = Pipeline('3:1:1', './')
ppl.run()

In [ ]:
unpickled_df = pd.read_pickle("ast.pkl")

In [ ]:
unpickled_df["code"]

In [ ]:
unpickled_df2 = pd.read_pickle("ast.pkl")
unpickled_df2

In [ ]:
unpickled_df2 = pd.read_pickle("_train.pkl")
unpickled_df2

In [ ]:
unpickled_df2 = pd.read_pickle("train/train_.pkl")
unpickled_df2

In [ ]:
from pipeline import *

In [ ]:
source = Pipeline.parse_source(output_file='ast.pkl',option='existing')

In [ ]:
ppl = Pipeline('3:1:1', './')
source = ppl.parse_source(output_file='ast.pkl',option='existing')

In [ ]:
source

In [ ]:
s = pd.read_csv('vdisc_train_buffer_over_data_small.csv.gz')

In [ ]:
x = []
x.append(s.groupby(['testcase_ID']).apply(
            process_for_subtree,
            axis='columns',
            meta=('processed_for_subtree', 'unicode'),
            ))

In [ ]:
x

In [ ]:
s

In [ ]:
labels = s.copy()
del labels['Unnamed: 0']
labels.drop_duplicates(subset ='testcase_ID', keep = False, inplace = True)
labels

In [ ]:
s1 = pd.read_csv('vdisc_train_buffer_over_data_small.csv.gz')
s1

In [ ]:
s['data'] = (s.groupby(['testcase_ID']).apply(
            process_for_subtree,
            axis='columns',
            meta=('processed_for_subtree', 'unicode'),
            ))

In [ ]:
s

In [ ]:
s.to_pickle('sast.pkl')

In [ ]:
ppl = Pipeline('3:1:1', './')
source = ppl.parse_source(output_file='ast.pkl',option='existing')

In [ ]:
source

In [ ]:
ppl2 = Pipeline('3:1:1', './')
source2 = ppl.parse_source(output_file='ast.pkl',option='existing')

In [ ]:
ppl = Pipeline('3:1:1', './')
source = ppl.parse_source(output_file='ast.pkl',option='existing')

In [ ]:
e = pd.read_csv('vdisc_train_buffer_over_data_small.csv.gz')
e

In [3]:
unpickled_df11 = pd.read_pickle("train/blocks.pkl")

In [4]:
unpickled_df11

,Unnamed: 0,testcase_ID,flaw_loc,filename,code,buffer
19094,4792,19094,NaN,test.c,"[[12, [4], [4], [2, [5, [15, [0, [1]]], [2]], ...",False
3134,212912,3134,NaN,test.c,"[[12, [4], [4], [4], [4], [4], [2, [9, [6], [6...",True
2701,184597,2701,NaN,test.c,"[[12, [4], [4], [2, [10, [0, [1]], [0, [16]], ...",True
18719,4413,18719,NaN,test.c,"[[12, [4], [2, [10, [0, [1]]], [10, [0, [1]]],...",False
20834,6560,20834,NaN,test.c,"[[12, [4], [2]]]",False
16225,1885,16225,NaN,test.c,"[[12, [4], [4], [2]], [4]]",False
15717,1368,15717,NaN,test.c,"[[12, [4]]]",False
28480,14323,28480,NaN,test.c,"[[12, [4, [14]], [4], [2, [9, [6]], [13, [0, [...",False
8819,594568,8819,NaN,test.c,"[[12, [4], [2, [9, [6]], [5, [0], [2, [13]]]]]...",True
3243,219407,3243,NaN,test.c,"[[12, [4], [4], [4], [2, [9, [6]], [10, [0, [1...",True
6036,405138,6036,NaN,test.c,"[[12, [4], [2, [9, [6]], [9, [6], [6]], [9, [6...",True
25532,11335,25532,NaN,test.c,"[[12, [4], [4], [2, [9, [6]], [5, [7, [0, [1]]...",False
21156,6889,21156,NaN,test.c,"[[12, [2, [5, [0], [2], [2]]]]]",False
12162,819997,12162,NaN,test.c,"[[12, [4], [2, [9, [6, [0, [10, [0, [1]]]]]], ...",True
19835,5543,19835,NaN,test.c,"[[12, [4, [8]], [2, [9, [6]], [9, [6, [8]], [6...",False
7321,492711,7321,NaN,test.c,"[[12, [4], [2, [9, [17], [6, [14]]], [9, [17],...",True
27427,13261,27427,NaN,test.c,"[[12, [4, [14]], [4, [14]], [4], [4], [4], [2,...",False
19039,4736,19039,NaN,test.c,"[[12, [4], [4], [2, [9, [6]], [5, [0], [2]], [...",False
10913,735216,10913,NaN,test.c,"[[12, [4], [2, [9, [6], [6]]]]]",True
17038,2707,17038,NaN,test.c,"[[12, [4, [14]], [4, [14]], [2, [9, [17], [6, ...",False
21373,7107,21373,NaN,test.c,"[[12, [4], [4], [2, [5, [0], [13, [8]]], [13, ...",False
23074,8835,23074,NaN,test.c,"[[12, [4], [2, [9, [17], [6, [14]]], [5, [7, [...",False
10190,685677,10190,NaN,test.c,"[[12, [4], [4], [2, [9, [6]], [9, [17], [6, [1...",True
2875,196727,2875,NaN,test.c,"[[12, [4], [4, [14]], [2, [5, [0], [2, [13]]]]...",True
16318,1979,16318,NaN,test.c,"[[12, [4], [2, [9, [6]], [9, [6, [0, [8]]]]]]]",False
1471,103887,1471,NaN,test.c,"[[12, [2, [9, [6]], [13, [8]]]]]",True
14927,571,14927,NaN,test.c,"[[12, [4], [2]]]",False
3343,224572,3343,NaN,test.c,"[[12, [4], [4], [4], [2]], [4], [4]]",True
24834,10620,24834,NaN,test.c,"[[12, [4], [2, [9, [6]], [5, [0], [5, [0], [2]...",False
6452,432595,6452,NaN,test.c,"[[12, [4], [4], [2, [5, [0], [2, [9, [6], [6]]...",True
...,...,...,...,...,...,...
19072,4769,19072,NaN,test.c,"[[12, [4], [4], [4], [2, [5, [0], [13, [8]]], ...",False
25991,11802,25991,NaN,test.c,"[[12, [4, [14]], [2, [13, [10, [0, [1]], [0, [...",False
13132,885388,13132,NaN,test.c,"[[12, [4], [4], [4], [4], [4], [4], [2, [9, [1...",True
18861,4556,18861,NaN,test.c,"[[12, [2, [9, [6]], [5, [0], [13]], [10, [0, [...",False
10463,703590,10463,NaN,test.c,"[[12, [4], [4], [4], [2, [9, [6, [0, [1]]]], [...",True
5289,352859,5289,NaN,test.c,"[[12, [4, [14]], [4], [2, [9, [6]], [9, [17], ...",True
8623,581947,8623,NaN,test.c,"[[12, [4], [4], [2, [5, [0], [2, [13, [8]]]], ...",True
10863,731507,10863,NaN,test.c,"[[12, [4], [4], [4], [2, [5, [0], [2]]]], [4],...",True
2252,154585,2252,NaN,test.c,"[[12, [4, [14]], [2, [9, [6, [0, [0, [16]]]]],...",True
7811,525438,7811,NaN,test.c,"[[12, [4], [2, [5, [0], [10, [0, [1]], [0, [16...",True
18472,4164,18472,NaN,test.c,"[[12, [4], [4], [4], [2, [5, [7, [0, [1]], [8]...",False
18190,3876,18190,NaN,test.c,"[[12, [4], [4], [2, [9, [6, [8], [42, [0, [8]]...",False
14835,477,14835,NaN,test.c,"[[12, [4], [2, [9, [17], [6, [14]]], [5, [0], ...",False
14049,946257,14049,NaN,test.c,"[[12, [4], [4], [4], [2, [9, [6]], [9, [6]], [...",True
17,1454,17,NaN,test.c,"[[12, [4], [2]]]",True
7452,501570,7452,NaN,test.c,"[[12, [4], [4, [14]], [2, [5, [0], [13, [8]]],...",True
5264,350530,5264,NaN,test.c,"[[12, [4], [4], [4], [4], [4], [4], [4, [4], [...",True
12272,826748,12272,NaN,test.c,"[[12, [4], [4], [2, [9, [17], [6, [14]]], [9, ...",True
5829,389799,5829,NaN,test.c,"[[12, [4], [4], [4], [4], [2, [9, [17], [6, [1...",True
27508,13342,27508,NaN,test.c,"[[12, [4], [2, [9, [6, [8]]], [5, [0], [2, [27...",False
10927,736024,10927,NaN,test.c,"[[12, [4], [4], [4], [2, [9, [6, [8]], [6, [7,...",True
18038,3722,18038,NaN,test.c,"[[12, [4], [2, [5, [0], [13, [8]]]]], [5, [0],...",False
11592,780536,11592,NaN,test.c,"[[12, [4, [14]], [2, [9, [17], [6, [14]]], [9,...",True
1322,94017,1322,NaN,test.c,"[[12, [4], [4], [4], [4], [2, [9, [6, [0, [1]]...",True
939,67027,939,NaN,test.c,"[[12, [4, [14]], [4, [14]], [4, [14]], [2, [9,...",True
11710,789275,11710,NaN,test.c,"[[12, [2, [9, [6], [6]], [9, [6, [0, [16]]]], ...",True
6842,461636,6842,NaN,test.c,"[[12, [4], [4], [4], [2, [5, [0], [2]]]], [4],...",True
12942,873341,12942,NaN,test.c,"[[12, [4], [4], [4], [4], [4], [4], [4], [2, [...",True
28384,14227,28384,NaN,test.c,"[[12, [4], [4], [2, [5, [0], [2, [13]]], [5, [...",False
3568,241029,3568,NaN,test.c,"[[12, [2, [5, [0], [13]], [10, [0, [1]]]]]]",True